replicaCount: 3

image:
  repository: ghcr.io/replace-me/todolist-app
  digest: ""
  pullPolicy: IfNotPresent

serviceAccount:
  name: todolist

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  minReplicas: 3
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
