apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "todolist.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todolist.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 5000
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "todolist.name" . }}
              app.kubernetes.io/component: cleanup
      ports:
        - protocol: TCP
          port: 5000
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: todolist
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
        - protocol: TCP
          port: 443
    - ports:
        - protocol: TCP
          port: 443
