apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "todolist.fullname" . }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todolist.name" . }}
