apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "todolist.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: http
